CREATE TABLE IF NOT EXISTS visitor_count (
  id INTEGER PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO visitor_count (id, count)
VALUES (1, 0)
ON CONFLICT(id) DO NOTHING;
